//! Core backtesting types and traits
//!
//! Defines the fundamental abstractions for GPU-accelerated backtesting:
//! - Strategy trait for user-defined trading logic
//! - ParameterGrid for optimization parameter ranges
//! - BacktestResult for performance metrics
//! - Signal types for trading decisions
//!
//! # Architecture
//!
//! ```text
//! Strategy (user-defined)
//!    ↓ implements
//! on_data() → Signal (Buy/Sell/Hold)
//!    ↓ collected by
//! BacktestEngine → BacktestResult (metrics)
//!    ↓ optimized by
//! GeneticOptimizer → OptimalParameters
//! ```

use std::collections::HashMap;

/// Trading signal generated by a strategy
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Signal {
    /// Enter long position (buy)
    Buy,
    /// Exit position (sell)
    Sell,
    /// Do nothing (hold current position)
    Hold,
    /// Enter short position
    Short,
    /// Cover short position
    Cover,
}

/// OHLCV bar data at a single point in time
#[derive(Debug, Clone)]
pub struct OHLCVBar {
    pub timestamp: i64,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
}

/// Pre-calculated indicator values for a bar
///
/// Contains all indicator results to avoid recalculation
pub type IndicatorValues = HashMap<String, f64>;

/// Trading strategy trait
///
/// Implement this trait to define custom trading logic.
///
/// # Example
///
/// ```rust,ignore
/// struct RSICrossover {
///     rsi_period: usize,
///     buy_threshold: f64,
///     sell_threshold: f64,
/// }
///
/// impl Strategy for RSICrossover {
///     fn on_data(&mut self, bar: &OHLCVBar, indicators: &IndicatorValues) -> Signal {
///         let rsi = indicators.get("rsi_14").unwrap_or(&50.0);
///         if *rsi < self.buy_threshold {
///             Signal::Buy
///         } else if *rsi > self.sell_threshold {
///             Signal::Sell
///         } else {
///             Signal::Hold
///         }
///     }
///
///     fn indicators(&self) -> Vec<IndicatorConfig> {
///         vec![IndicatorConfig::RSI { period: self.rsi_period }]
///     }
/// }
/// ```
pub trait Strategy: Send + Sync {
    /// Called for each new bar with pre-calculated indicators
    ///
    /// Returns a trading signal (Buy/Sell/Hold/Short/Cover)
    fn on_data(&mut self, bar: &OHLCVBar, indicators: &IndicatorValues) -> Signal;

    /// List of indicators required by this strategy
    ///
    /// Engine will pre-calculate these before calling on_data()
    fn indicators(&self) -> Vec<IndicatorConfig>;

    /// Parameter grid for optimization (optional)
    ///
    /// Default implementation returns empty grid (no optimization)
    fn parameters(&self) -> ParameterGrid {
        ParameterGrid::default()
    }

    /// Initial capital for backtesting (default: $10,000)
    fn initial_capital(&self) -> f64 {
        10_000.0
    }

    /// Position sizing logic (default: 100% of capital)
    fn position_size(&self, _equity: f64, _signal: Signal) -> f64 {
        1.0 // Full allocation
    }
}

/// Indicator configuration for backtesting
#[derive(Debug, Clone, PartialEq)]
pub enum IndicatorConfig {
    RSI {
        period: usize,
    },
    ATR {
        period: usize,
    },
    SMA {
        period: usize,
    },
    EMA {
        period: usize,
    },
    MACD {
        fast: usize,
        slow: usize,
        signal: usize,
    },
    Stochastic {
        k_period: usize,
        d_period: usize,
    },
    BollingerBands {
        period: usize,
        std_dev: f64,
    },
    CCI {
        period: usize,
    },
    ROC {
        period: usize,
    },
    WilliamsR {
        period: usize,
    },
}

impl IndicatorConfig {
    /// Get unique identifier for this indicator configuration
    pub fn key(&self) -> String {
        match self {
            IndicatorConfig::RSI { period } => format!("rsi_{}", period),
            IndicatorConfig::ATR { period } => format!("atr_{}", period),
            IndicatorConfig::SMA { period } => format!("sma_{}", period),
            IndicatorConfig::EMA { period } => format!("ema_{}", period),
            IndicatorConfig::MACD { fast, slow, signal } => {
                format!("macd_{}_{}_{}", fast, slow, signal)
            }
            IndicatorConfig::Stochastic { k_period, d_period } => {
                format!("stoch_{}_{}", k_period, d_period)
            }
            IndicatorConfig::BollingerBands { period, std_dev } => {
                format!("bb_{}_{}", period, std_dev)
            }
            IndicatorConfig::CCI { period } => format!("cci_{}", period),
            IndicatorConfig::ROC { period } => format!("roc_{}", period),
            IndicatorConfig::WilliamsR { period } => format!("williams_{}", period),
        }
    }
}

/// Parameter grid for strategy optimization
///
/// Defines ranges for parameters to test during optimization
#[derive(Debug, Clone, Default)]
pub struct ParameterGrid {
    pub ranges: HashMap<String, ParameterRange>,
}

impl ParameterGrid {
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a parameter range to the grid
    pub fn add_range(&mut self, name: impl Into<String>, range: ParameterRange) {
        self.ranges.insert(name.into(), range);
    }

    /// Total number of parameter combinations
    pub fn size(&self) -> usize {
        if self.ranges.is_empty() {
            return 1;
        }
        self.ranges.values().map(|r| r.len()).product()
    }

    /// Check if grid is empty
    pub fn is_empty(&self) -> bool {
        self.ranges.is_empty()
    }
}

/// Parameter range for optimization
#[derive(Debug, Clone)]
pub enum ParameterRange {
    /// Integer range with step
    Int { min: i64, max: i64, step: i64 },
    /// Float range with step
    Float { min: f64, max: f64, step: f64 },
    /// Discrete values
    Values(Vec<f64>),
}

impl ParameterRange {
    /// Number of values in this range
    pub fn len(&self) -> usize {
        match self {
            ParameterRange::Int { min, max, step } => ((*max - *min) / *step + 1) as usize,
            ParameterRange::Float { min, max, step } => (((*max - *min) / *step) as usize) + 1,
            ParameterRange::Values(v) => v.len(),
        }
    }

    /// Check if range is empty
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Get value at index
    pub fn get(&self, index: usize) -> Option<f64> {
        match self {
            ParameterRange::Int { min, step, .. } => Some((*min + (*step * index as i64)) as f64),
            ParameterRange::Float { min, step, .. } => Some(*min + (*step * index as f64)),
            ParameterRange::Values(v) => v.get(index).copied(),
        }
    }
}

/// Result of a backtest run
#[derive(Debug, Clone)]
pub struct BacktestResult {
    /// Strategy parameters used
    pub parameters: HashMap<String, f64>,

    /// Equity curve over time
    pub equity_curve: Vec<f64>,

    /// Final equity
    pub final_equity: f64,

    /// Total return (%)
    pub total_return: f64,

    /// Sharpe ratio (annualized)
    pub sharpe_ratio: f64,

    /// Maximum drawdown (%)
    pub max_drawdown: f64,

    /// Win rate (%)
    pub win_rate: f64,

    /// Total number of trades
    pub num_trades: usize,

    /// Profit factor (gross profit / gross loss)
    pub profit_factor: f64,

    /// All trades executed
    pub trades: Vec<Trade>,
}

impl BacktestResult {
    /// Create empty result
    pub fn empty() -> Self {
        Self {
            parameters: HashMap::new(),
            equity_curve: Vec::new(),
            final_equity: 0.0,
            total_return: 0.0,
            sharpe_ratio: 0.0,
            max_drawdown: 0.0,
            win_rate: 0.0,
            num_trades: 0,
            profit_factor: 0.0,
            trades: Vec::new(),
        }
    }

    /// Fitness score for optimization (higher is better)
    ///
    /// Uses Sharpe ratio with max drawdown penalty
    pub fn fitness(&self) -> f64 {
        // Penalize high drawdown
        let drawdown_penalty = 1.0 - (self.max_drawdown / 100.0).min(1.0);
        self.sharpe_ratio * drawdown_penalty
    }
}

/// Individual trade record
#[derive(Debug, Clone)]
pub struct Trade {
    pub entry_time: i64,
    pub exit_time: i64,
    pub entry_price: f64,
    pub exit_price: f64,
    pub quantity: f64,
    pub direction: TradeDirection,
    pub pnl: f64,
    pub pnl_percent: f64,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TradeDirection {
    Long,
    Short,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parameter_grid_size() {
        let mut grid = ParameterGrid::new();
        grid.add_range(
            "rsi_period",
            ParameterRange::Int {
                min: 10,
                max: 20,
                step: 2,
            },
        );
        grid.add_range(
            "threshold",
            ParameterRange::Float {
                min: 30.0,
                max: 40.0,
                step: 5.0,
            },
        );

        assert_eq!(grid.size(), 6 * 3); // 6 RSI periods × 3 thresholds = 18 combinations
    }

    #[test]
    fn test_parameter_range_get() {
        let range = ParameterRange::Int {
            min: 10,
            max: 20,
            step: 2,
        };
        assert_eq!(range.get(0), Some(10.0));
        assert_eq!(range.get(1), Some(12.0));
        assert_eq!(range.get(5), Some(20.0));
    }

    #[test]
    fn test_indicator_config_key() {
        let rsi = IndicatorConfig::RSI { period: 14 };
        assert_eq!(rsi.key(), "rsi_14");

        let macd = IndicatorConfig::MACD {
            fast: 12,
            slow: 26,
            signal: 9,
        };
        assert_eq!(macd.key(), "macd_12_26_9");
    }
}
