"""Configuration module for kimsfinance."""

from __future__ import annotations

from .gpu_thresholds import (
    GPU_THRESHOLDS,
    get_threshold,
    should_use_gpu_complex,
    should_use_gpu_histogram,
    should_use_gpu_iterative,
    should_use_gpu_rolling,
    should_use_gpu_simple,
)
from .layout_constants import (
    BOX_SIZE_ATR_MULTIPLIER,
    BOX_SIZE_FALLBACK_RATIO,
    BRICK_SPACING_RATIO,
    CENTER_OFFSET,
    CHART_HEIGHT_RATIO,
    COLUMN_BOX_WIDTH_RATIO,
    DEFAULT_LINE_WIDTH,
    FILL_AREA_ALPHA,
    GRID_ALPHA,
    GRID_LINE_WIDTH,
    HORIZONTAL_GRID_DIVISIONS,
    MAX_VERTICAL_GRID_LINES,
    MIN_BODY_HEIGHT,
    MIN_BOX_HEIGHT,
    MIN_BRICK_HEIGHT,
    MIN_WICK_WIDTH,
    QUARTER_OFFSET,
    SPACING_RATIO,
    THREE_QUARTER_OFFSET,
    TICK_LENGTH_RATIO,
    VOLUME_ALPHA,
    VOLUME_HEIGHT_RATIO,
    WICK_WIDTH_RATIO,
)
from .render_config import RenderConfig

__all__ = [
    "GPU_THRESHOLDS",
    "get_threshold",
    "should_use_gpu_simple",
    "should_use_gpu_complex",
    "should_use_gpu_iterative",
    "should_use_gpu_histogram",
    "should_use_gpu_rolling",
    "RenderConfig",
    # Layout constants
    "CHART_HEIGHT_RATIO",
    "VOLUME_HEIGHT_RATIO",
    "SPACING_RATIO",
    "WICK_WIDTH_RATIO",
    "TICK_LENGTH_RATIO",
    "CENTER_OFFSET",
    "QUARTER_OFFSET",
    "THREE_QUARTER_OFFSET",
    "GRID_LINE_WIDTH",
    "GRID_ALPHA",
    "VOLUME_ALPHA",
    "FILL_AREA_ALPHA",
    "BOX_SIZE_ATR_MULTIPLIER",
    "BOX_SIZE_FALLBACK_RATIO",
    "COLUMN_BOX_WIDTH_RATIO",
    "BRICK_SPACING_RATIO",
    "MIN_WICK_WIDTH",
    "MIN_BODY_HEIGHT",
    "MIN_BRICK_HEIGHT",
    "MIN_BOX_HEIGHT",
    "HORIZONTAL_GRID_DIVISIONS",
    "MAX_VERTICAL_GRID_LINES",
    "DEFAULT_LINE_WIDTH",
]
